#rename the app using this https://stackoverflow.com/questions/49353199/how-to-change-the-app-display-name-build-with-flutter?rq=1
name: dietAcademy
description: A new Flutter project.

# follow this https://semver.org/
version: 1.0.0+1
#flutter version 1.20.2
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:  
  #part of the skeleton
  http: ^0.12.0+2
  shared_preferences: ^0.5.10
  fluttertoast: ^7.0.2
  provider: ^4.3.2+1
  get_storage: ^1.3.2
  path_provider: ^1.6.14
  flushbar: ^1.10.4
  keyboard_avoider: ^0.1.2
  flutter_keyboard_visibility: ^3.3.0
  permission_handler: ^5.0.1
  email_validator: ^1.0.4
  material_color_scheme: ^0.0.2
  intl: ^0.16.1
  firebase_messaging: ^7.0.0
  firebase_core: ^0.5.0
  global_configuration: ^1.6.0
  flutter:
    sdk: flutter
  #part of the skeleton
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/icon.png"
  image_path_android: "assets/icons/icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/cfg/
    - assets/images/
    - assets/icons/
    - locales/
flutter_intl:
  enabled: true